# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '/home/vsts/work/1/s/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode'
    veracodeAppProfile: 'Verademo .NET'
    version: '$(build.buildNumber)'
    filepath: '/home/vsts/work/1/s/$(Build.BuildId).zip'
    createSandBox: false
    createProfile: false
    failTheBuildIfVeracodeScanDidNotInitiate: true
    scanStatusCheckInterval: '60'
    importResults: false
    failBuildOnPolicyFail: true